# Generated by Django 2.2.5 on 2019-09-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='shipping_cost',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8),
        ),
    ]
