# Generated by Django 2.2.5 on 2019-09-29 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo_store', '0002_size_shipping_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='size_id',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
