# Generated by Django 2.2.5 on 2019-09-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_store', '0003_auto_20190929_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='data',
            field=models.ImageField(upload_to='./images'),
        ),
    ]
